services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - '${POSTGRES_PORT}:5432'

  backend:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URI: ${DATABASE_URI}
      JWT_SECRET: ${JWT_SECRET}
      JWT_ACCESS_TOKEN_EXPIRATION: ${JWT_ACCESS_TOKEN_EXPIRATION}
      JWT_REFRESH_TOKEN_EXPIRATION: ${JWT_REFRESH_TOKEN_EXPIRATION}
      COOKIE_DOMAIN: ${COOKIE_DOMAIN}
      FRONTEND_DEV_URL: ${FRONTEND_DEV_URL}
      FRONTEND_PROD_URL: ${FRONTEND_PROD_URL}
      NODE_ENV: ${NODE_ENV}
      SUPABASE_URL: ${SUPABASE_URL}
      SUPABASE_ANON_KEY: ${SUPABASE_ANON_KEY}
      SUPABASE_SERVICE_ROLE_KEY: ${SUPABASE_SERVICE_ROLE_KEY}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
    ports:
      - '${PORT}:8000'
    volumes:
      - ./src:/usr/src/app/src
    command: sh -c "npx prisma generate && npx prisma migrate deploy && pnpm start:dev"

volumes:
  db_data:
